services:
  rerum:
    build: .
    ports: 
      - "3001:3001"
    depends_on:
      - localauth0
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  localauth0:
    image: public.ecr.aws/primaassicurazioni/localauth0:0.8.2
    healthcheck:
      test: ["CMD", "/localauth0", "healthcheck"]
    ports:
      - "3002:3002"  # Or any other port you choose
    environment:
      - AUTH0_DOMAIN=local_rerum.auth0.com  # Replace with your Auth0 domain
      - AUTH0_CLIENT_ID=rerum      # Replace with your client ID
      - AUTH0_CLIENT_SECRET=rerum # Replace with your client secret
      - AUTH0_CALLBACK_URL=http://localhost:3001/callback # Replace with your app's callback URL
    restart: "no"