#!/usr/bin/env node
const router = require('express').Router()
const controller = require('../db-controller.js')
const bodyParser = require('body-parser')
const jsonParser = bodyParser.json()

// Set default API response
router.get('/', function (req, res) {
    res.json({
        message: 'Welcome to v1 in nodeJS!'
    })
})

// API routes.  Test deploy pipelines.

// api/test to just return some JSON, no DB interactions
router.route('/api/test')
    .get(controller.index)

// api/getByID/_id to fire a request for http://devstore.rerum.io/v1/id/11111 from annotationStoreDev on img-01
router.route('/id/:_id')
    .get(controller.id)

// api/getByProps handles a POST with body that is a JSON object of properties to match on.
router.route('/api/query')
    .post(controller.query, jsonParser)

// api/create handles a POST whose body is to be created.  _id generated by mongoose before saving.  Uses insertOne for now.
router.route('/api/create')
    .post(controller.create, jsonParser)

// POST with body that is a JSON object to be overwritten (must have @id).  Uses replaceOne for now.
router.route('/api/overwrite')
    .put(controller.overwrite, jsonParser)
    
// Export API routes
module.exports = router
