name: RERUM v1 Deploy
on: 
  push:
    branches:
      main
  pull_request:
    branches:
      main
jobs:
    deploy:
      # Deploy to newprd01 and newdev01
      strategy: 
        matrix:
            node-version: [16]
            machines: [vlcdhprdp02, vlcdhp02]
      runs-on: ${{ matrix.machines }}
      steps:
        - uses: actions/checkout@v3
        - run: |
            if [[ ! -e /opt/nodeapps/logs/rerumv1.txt ]]; then
                mkdir -p /opt/nodeapps/logs
                touch /opt/nodeapps/logs/rerumv1.txt
            fi
            cd /opt/nodeapps/v1-node/
            pm2 stop rerum_v1
            git stash
            git pull
            npm install
            pm2 start -i max bin/rerum_v1.js
