name: RERUM v1 Deploy
on: 
  push:
    branches:
      main
jobs:
    deploy:
      strategy: 
        matrix:
            node-version: [16]
            machines: [vlcdhp02, vlcdhprdp02]
      runs-on: ${{ matrix.machines }}
      steps:
        - uses: actions/checkout@v3
        - run: |
            if [[ ! -e /srv/node/logs/rerumv1.txt ]]; then
                mkdir -p /srv/node/logs
                touch /srv/node/logs/rerumv1.txt
            fi
            cd /srv/node/v1-node/
            pm2 stop rerum_v1
            git stash
            git pull
            npm install
            pm2 start -i max bin/rerum_v1.js
